//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTStore.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNG_UserToken
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public bool IsForgotPasswordToken { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> ExpireDatetime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public bool IsUsed { get; set; }
        public Nullable<System.DateTime> UsedDatetime { get; set; }
        public string UsedBy { get; set; }
        public bool IsClosed { get; set; }
    }
}
