//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Finance.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNG_CatType
    {
        public string CatTypeCode { get; set; }
        public string CatTypeName { get; set; }
        public string CatTypeGroup { get; set; }
        public bool IsDeleted { get; set; }
    }
}
