//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTStore.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNG_Menu
    {
        public System.Guid MenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string Note { get; set; }
        public bool IsEnable { get; set; }
        public string Action { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Icon { get; set; }
        public bool IsDeleted { get; set; }
    }
}
