//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTStore.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNG_Category
    {
        public System.Guid CatID { get; set; }
        public string CatCode { get; set; }
        public string CatTypeCode { get; set; }
        public string CatName { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ExpandProperties { get; set; }
        public string SubCatTypeCode { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Value { get; set; }
    }
}
