//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Finance.Models.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagementWarehouseEntities : DbContext
    {
        public ManagementWarehouseEntities()
            : base("name=ManagementWarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<MNG_Category> MNG_Category { get; set; }
        public virtual DbSet<MNG_CatType> MNG_CatType { get; set; }
        public virtual DbSet<MNG_HistoryLogin> MNG_HistoryLogin { get; set; }
        public virtual DbSet<MNG_Menu> MNG_Menu { get; set; }
        public virtual DbSet<MNG_RoleInMenu> MNG_RoleInMenu { get; set; }
        public virtual DbSet<MNG_UserToken> MNG_UserToken { get; set; }
        public virtual DbSet<MNG_Version> MNG_Version { get; set; }
    }
}
